version: '3'
services:
  mysql:
    image: mon-mysql:latest
    ports:
      - "3306:3306"
    # Autres configurations du service 1

  kaddem:
    image: kaddem:v1
    ports:
      - "8089:8089"
    # Autres configurations du service 2
