version: '3.1'
services:
  db:
    image: mysql
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: khaddemApp
    networks:
      - mynetwork

  back:
    depends_on:
      - db
    image: khalilkhemiri/mohamedkhalil-5sae-g5-khaddem:latest
    container_name: back
    restart: on-failure
    ports:
      - "6868:8089"
    stdin_open: true
    tty: true
    networks:
      - mynetwork



volumes:
  mysql_data:

networks:
  mynetwork:
