FROM openjdk:11-oracle

ENV NEXUS_URL=http://192.168.33.10//:8081/repository/maven-releases/
ENV GROUP_ID=tn/esprit/spring
ENV ARTIFACT_ID=khaddem
ENV ARTIFACT_VERSION=4.0
ENV ARTIFACT_PACKAGING=jar


EXPOSE 8089
RUN curl -o /${ARTIFACT_ID}-${ARTIFACT_VERSION}.${ARTIFACT_PACKAGING} ${NEXUS_URL}${GROUP_ID}/${ARTIFACT_ID}/${ARTIFACT_VERSION}/${ARTIFACT_ID}-${ARTIFACT_VERSION}.${ARTIFACT_PACKAGING}

CMD java -jar /${ARTIFACT_ID}-${ARTIFACT_VERSION}.${ARTIFACT_PACKAGING}